python \
    pretrain_gpt.py \
    --tokenizer-type \
    HuggingFaceTokenizer \
    --tokenizer-model \
    unsloth/DeepSeek-V3 \
    --num-layers \
    43 \
    --hidden-size \
    4096 \
    --num-attention-heads \
    64 \
    --kv-channels \
    512 \
    --max-position-embeddings \
    4096 \
    --normalization \
    RMSNorm \
    --norm-epsilon \
    1e-6 \
    --swiglu \
    --disable-bias-linear \
    --untie-embeddings-and-output-weights \
    --position-embedding-type \
    rope \
    --rotary-base \
    10000 \
    --make-vocab-size-divisible-by \
    3232 \
    --multi-latent-attention \
    --q-lora-rank \
    1024 \
    --qk-pos-emb-head-dim \
    64 \
    --v-head-dim \
    512 \
    --rotary-scaling-factor \
    4 \
    --mscale \
    1.0 \
    --mscale-all-dim \
    1.0 \
    --qk-layernorm \
    --o-groups \
    8 \
    --o-lora-rank \
    1024 \
    --original-max-position-embeddings \
    65536 \
    --experimental-attention-variant \
    dsv4_hybrid \
    --csa-window-size \
    128 \
    --csa-compress-ratios \
    ([0,0,4]+[128,4]*20+[0]) \
    --csa-compress-rotary-base \
    40000 \
    --dsa-indexer-n-heads \
    64 \
    --dsa-indexer-head-dim \
    128 \
    --dsa-indexer-topk \
    512 \
    --dsa-indexer-loss-coeff \
    1e-2 \
    --dsa-indexer-use-sparse-loss \
    --num-experts \
    256 \
    --moe-n-hash-layers \
    3 \
    --moe-ffn-hidden-size \
    2048 \
    --moe-shared-expert-intermediate-size \
    2048 \
    --moe-router-load-balancing-type \
    seq_aux_loss \
    --moe-router-topk \
    6 \
    --moe-aux-loss-coeff \
    1e-4 \
    --moe-router-topk-scaling-factor \
    1.5 \
    --moe-router-score-function \
    sqrtsoftplus \
    --moe-router-enable-expert-bias \
    --moe-router-bias-update-rate \
    1e-3 \
    --activation-func-clamp-value \
    10.0 \
    --enable-hyper-connections \
    --num-residual-streams \
    4 \
    --mhc-sinkhorn-iterations \
    20 \
    --use-fused-mhc \
    --mtp-num-layers \
    1 \
    --mtp-loss-scaling-factor \
    0.1 \
    --attention-dropout \
    0.0 \
    --hidden-dropout \
    0.0 \
    --seq-length \
    4096 \
    --split \
    99,1,0 \
    --no-mmap-bin-files \
    --num-workers \
    6 \
    --data-cache-path \
    ./data_cache \
    --tensor-model-parallel-size \
    1 \
    --pipeline-model-parallel-size \
    2 \
    --expert-model-parallel-size \
    64 \
    --context-parallel-size \
    1 \
    --expert-tensor-parallel-size \
    1 \
    --pipeline-model-parallel-layout \
    Et*4|(tttttt|)*6tttmL \
    --use-distributed-optimizer \
    --sequence-parallel \
    --overlap-grad-reduce \
    --overlap-param-gather \
    --moe-token-dispatcher-type \
    flex \
    --moe-flex-dispatcher-backend \
    hybridep \
    --moe-hybridep-num-sms \
    32 \
    --moe-grouped-gemm \
    --moe-permute-fusion \
    --moe-router-fusion \
    --moe-router-dtype \
    fp32 \
    --moe-router-force-load-balancing \
    --cuda-graph-impl \
    transformer_engine \
    --cuda-graph-modules \
    attn \
    moe_router \
    moe_preprocess \
    --te-rng-tracker \
    --cuda-graph-warmup-steps \
    1 \
    --use-mcore-models \
    --use-flash-attn \
    --transformer-impl \
    transformer_engine \
    --micro-batch-size \
    1 \
    --global-batch-size \
    2048 \
    --train-samples \
    585937500 \
    --exit-duration-in-mins \
    220 \
    --no-save-optim \
    --no-check-for-nan-in-loss-and-grad \
    --cross-entropy-loss-fusion \
    --cross-entropy-fusion-impl \
    te \
    --no-create-attention-mask-in-dataloader \
    --manual-gc \
    --manual-gc-interval \
    10 \
    --lr \
    3.9e-06 \
    --min-lr \
    3.9e-07 \
    --lr-warmup-init \
    3.9e-07 \
    --lr-decay-style \
    cosine \
    --lr-decay-samples \
    584765624 \
    --lr-warmup-samples \
    1536000 \
    --weight-decay \
    0.1 \
    --clip-grad \
    1.0 \
    --adam-beta1 \
    0.9 \
    --adam-beta2 \
    0.95 \
    --bf16 \
    --fp8-recipe \
    mxfp8 \
    --fp8-format \
    e4m3 \
    --fp8-param-gather \
    --reuse-grad-buf-for-mxfp8-param-ag \
    --use-precision-aware-optimizer \
    --main-grads-dtype \
    fp32 \
    --main-params-dtype \
    fp32 \
    --exp-avg-dtype \
    bf16 \
    --exp-avg-sq-dtype \
    bf16 \
    --moe-router-padding-for-quantization \
    --init-method-std \
    0.02 \
    --eval-iters \
    32 \
    --eval-interval \
    200 \
    --no-load-optim \
    --no-load-rng \
    --auto-detect-ckpt-format \
    --load \
     \
    --save-interval \
    500 \
    --dist-ckpt-strictness \
    log_all \
    --log-throughput \
    --log-interval \
    1 \
    --logging-level \
    20 \
    --log-timers-to-tensorboard \
    --log-memory-to-tensorboard \
    --log-validation-ppl-to-tensorboard \
    --tensorboard-dir \
    ./tensorboard \
    --enable-experimental \
    --log-memory-interval \
    5 \
    --data-path \
    /lustre/share/coreai_devtech_all/Dataset/Slimpajama/DeepSeek-V3/dsv3_text_document \
